name: Release a new VTD app version

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build_and_release:
    name: Build & Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run make

      - name: Upload assets to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            out/make/squirrel.windows/x64/*.exe
            out/make/deb/x64/*.deb
            out/make/rpm/x64/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
